CQA/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CQA.Resources;

namespace CQA.Models
{
    public class Question
    {

        public int QuestionId { get; set; }

        public int QuestionFileId { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.MultilineText)]
        public string QuestionText { get; set; }

        public string Hint { get; set; }

        public string ImageUri { get; set; }

        public bool IsActive { get; set; }

        public int SubjectId { get; set; }
        public virtual Subject Subject { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<UsersAction> UsersActions { get; set; }
        public virtual ICollection<QuestionView> QuestionViews { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }

    }
}

CQA/Models/QuestionView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CQA.Models
{
    public class QuestionView
    {

        public int UserId { get; set; }
        public virtual UserProfile User { get; set; }

        public int QuestionId { get; set; }
        public virtual Question Question { get; set; }

        public DateTime ViewDate { get; set; }

    }
}

CQA/Models/Setup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data;
using System.Linq;
using System.Web;

namespace CQA.Models
{
    public class Setup : DateCreatedModel //: INotifyPropertyChanged
    {
        //public event PropertyChangedEventHandler PropertyChanged;

        //public Setup()
        //{
        //    this.PropertyChanged += new PropertyChangedEventHandler(CreateSetupsProbabilityChange);
        //}

        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int SetupId { get; set; }

        [Required]
        [DisplayName("Názov (rok)")]
        public string Name { get; set; }

        [DisplayName("Aktívny")]
        public bool Active { get; set; }

        [DisplayName("Zobrazený")]
        public bool Displayed { get; set; }

        [DisplayName("Meno predmetu")]
        public int SubjectId { get; set; }
        [DisplayName("Meno predmetu")]
        public virtual Subject Subject { get; set; }
        
        private int _answeringProbability = 0;
        [DisplayName("Počet hodnotení na jednu odpoveď")]
        [Required]
        [Range(1, 50)]
        public int AnsweringProbability 
        { 
            get { return _answeringProbability; }
            set {
                _answeringProbability = value;
                //OnPropertyChanged("AnsweringProbability"); 
            } 
        }

        public DateTime StartDate { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }

        public virtual ICollection<UsersSetup> UsersSetups { get; set; }
        //not needed right now
        //public virtual ICollection<SetupsStatistics> SetupsStatistics { get; set; }
        public virtual ICollection<SetupsProbabilityChange> SetupsProbabilityChanges { get; set; }


        // Create the OnPropertyChanged method to raise the event 
        //protected void OnPropertyChanged(string name)
        //{
        //    PropertyChangedEventHandler handler = PropertyChanged;
        //    if (handler != null)
        //    {
        //        handler(this, new PropertyChangedEventArgs(name));
        //    }
        //}

    }
}

CQA/Controllers/SetupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CQA.Models;
using WebMatrix.WebData;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Extensions;
using CQA.Jobs;
//using Excel = Microsoft.Office.Interop.Excel; 

namespace CQA.Controllers
{

    [Authorize(Roles = "Admin")] 
    public class SetupsController : Controller
    {
        private CQADBContext db = new CQADBContext();

        //
        // GET: /Setups/

        public ActionResult Index()
        {
            var setup = db.Setups.Include(s => s.Subject);
            return View(setup.ToList());
        }

        //
        // GET: /Setups/Details/5

        public ActionResult Details(int id = 0)
        {
            Setup setup = db.Setups.Find(id);
            if (setup == null)
            {
                return HttpNotFound();
            }
            return View(setup);
        }

        //
        // GET: /Setups/Create

        public ActionResult Create()
        {
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "Name");
            Setup s = new Setup();
            s.AnsweringProbability = 10;
            s.Active = true;
            return View(s);
        }

        //
        // POST: /Setups/Create

        [HttpPost]
        public ActionResult Create(Setup setup)
        {
            if (ModelState.IsValid)
            {
                setup.StartDate = DateTime.Now;
                db.Setups.Add(setup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "Name", setup.SubjectId);
            return View(setup);
        }

        //
        // GET: /Setups/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Setup setup = db.Setups.Find(id);
            if (setup == null)
            {
                return HttpNotFound();
            }
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "Name", setup.SubjectId);
            return View(setup);
        }

        //
        // POST: /Setups/Edit/5

        [HttpPost]
        public ActionResult Edit(Setup setup)
        {
            Setup original = db.Setups.Find(setup.SetupId);
            if (ModelState.IsValid)
            {
                int originValue = original.AnsweringProbability;

                setup.DateCreated = original.DateCreated;
                db.Entry(original).CurrentValues.SetValues(setup);
                db.SaveChanges();

                if (setup.AnsweringProbability != originValue)
                    SetupsProbabilityChange.CreateSetupsProbabilityChange(setup.SetupId,setup.AnsweringProbability);

                return RedirectToAction("Index");
            }
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectId", "Name", setup.SubjectId);
            return View(setup);
        }

        //
        // GET: /Setups/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Setup setup = db.Setups.Find(id);
            if (setup == null)
            {
                return HttpNotFound();
            }
            return View(setup);
        }

        //
        // POST: /Setups/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Setup setup = db.Setups.Find(id);
            db.Setups.Remove(setup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult ConvertOldNotifications()
        {
            foreach (Answer ans in db.Answers.Where(a => a.SeenEvaluation == false).ToList())
            {
                Notification not = new Notification();
                
                not.AnswerId = ans.AnswerId;
                not.NotificationFor = NotificationFor.MyAnswer;
                not.User = ans.Author;
                not.NotificationType = NotificationType.NewEvaluation;
                db.Notifications.Add(not);
                db.SaveChanges();
            }

            return RedirectToAction("Index","Home");
        }

        public ActionResult GetBasicStatistics()
        {
            using (StreamWriter sw = new StreamWriter(Server.MapPath("~/Reports/") + "stats.csv", false))
            {
                sw.WriteLine("pocet hodnoteni ;" + db.Ratings.Count());
                sw.WriteLine("pocet odpovedi ;" + db.Answers.Count());
                sw.WriteLine("dostatocne ohodnotenych ;" + db.Answers.Where(a => a.Evaluations.Count() == 16).Count());

                List<UserProfile> users = db.UserProfiles.OrderBy(u => u.Evaluations.Count()).ToList();
                foreach (UserProfile u in users)
                {
                    sw.WriteLine(u.RealName + ";" + u.Evaluations.Count() + ";" + u.UsersActions.Where(a => a.Action == UserActionType.SkippedAnswering || a.Action == UserActionType.SkippedEvaluation).Count() );
                }
                
            }
            ViewBag.Link = Request.Url.GetLeftPart(UriPartial.Authority)+"/Reports/stats.csv";
            return View();
        }

        [HttpPost]
        public ActionResult AddAnswers(HttpPostedFileBase file, int setupId)
        {
            var reader = new StreamReader(file.InputStream, Encoding.UTF8);
            List<string> columnNames = new List<string>();

            System.Globalization.CultureInfo customCulture = (System.Globalization.CultureInfo)System.Threading.Thread.CurrentThread.CurrentCulture.Clone();
            customCulture.NumberFormat.NumberDecimalSeparator = ".";

            System.Threading.Thread.CurrentThread.CurrentCulture = customCulture;
            Setup s = db.Setups.Find(setupId);

            var firstLine = reader.ReadLine();

            while (!reader.EndOfStream)
            {
                var Line = reader.ReadLine();
                var values = Line.Split(';');

                int id = Convert.ToInt32(values[0]);
                var q = db.Questions.Where(que => que.SubjectId == s.SubjectId && que.QuestionFileId == id).ToList().First();
               

                Answer a = new Answer();
                a.Text = values[1];
                a.Question = q;
                a.SetupId = setupId;
                db.Answers.Add(a);
                db.SaveChanges();

            }

            return RedirectToAction("Details", new { id = setupId });
        }

        [HttpPost]
        public ActionResult SetStartDate(int setupId, string date)
        {
            var l = date.Split('/');
            Setup setup = db.Setups.Find(setupId);
            setup.StartDate = new DateTime(Convert.ToInt32(l[2]), Convert.ToInt32(l[0]),Convert.ToInt32(l[1]));
            db.Entry(setup).State = EntityState.Modified;
            db.SaveChanges();

            return new HttpStatusCodeResult((int)HttpStatusCode.OK);
        }

        [HttpGet]
        public ActionResult GetReport(int setupId)
        {

           Setup s = db.Setups.SingleOrDefault(set => set.SetupId == setupId);
           Int32 unixTimestamp = (Int32)(DateTime.Now.Subtract(new DateTime(1970, 1, 1))).TotalSeconds;

           MemoryStream stream = Report.GetReport(setupId);

           //Write to response stream
           Response.Clear();
           Response.AddHeader("content-disposition", String.Format("attachment;filename={0}", "report_" + s.Subject.Name + "_" + unixTimestamp.ToString()+".xlsx"));
           Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

           stream.WriteTo(Response.OutputStream);
           Response.End();

            //Excel.Application xlApp;
            //I  xlWorkSheet;
            //object misValue = System.Reflection.Missing.Value;

            //xlApp = new Excel.Application();
            //xlWorkBook = xlApp.Workbooks.Add(misValue);

            //xlWorkSheet = (Excel.Worksheet)xlWorkBook.Worksheets.get_Item(1);
            //xlWorkSheet.Name = "QALO aktivita (po týždňoch)";

            //Setup s = db.Setups.SingleOrDefault(set => set.SetupId == setupId);
            //DateTime start = s.StartDate;

            //int k = 2;
            ////active users
            //while (start.AddDays(7) < DateTime.Now)
            //{
            //    start = start.AddDays(7);
            //    xlWorkSheet.Cells[1, k] = "k " + start.ToString();
            //    k++;
            //}

            //k = 2;
            //start = s.StartDate;
            ////active users
            //while (start.AddDays(7) < DateTime.Now)
            //{
            //    start = start.AddDays(7);
            //    xlWorkSheet.Cells[2, 1] = "Počet zapojených študentov";
            //    xlWorkSheet.Cells[2, k] = db.UsersSetups.Where(us => us.SetupId == setupId && us.DateCreated <= start).ToList().Count.ToString();
            //    k++;
            //}

            //start = s.StartDate;
            //k = 2;
            ////evaluations : users
            //while (start.AddDays(7) < DateTime.Now)
            //{
            //    start = start.AddDays(7);
            //    int sCount = db.UsersSetups.Where(us => us.SetupId == setupId && us.DateCreated <= start).ToList().Count;
            //    int eCount = db.Ratings.Where(e => e.Answer.SetupId == setupId && e.DateCreated <= start).ToList().Count;

            //    xlWorkSheet.Cells[3, 1] = "Priemer hodnotení na študenta";
            //    if (sCount != 0)
            //        xlWorkSheet.Cells[3, k] = ((double)((double)eCount / sCount)).ToString("#.###");
            //    else
            //        xlWorkSheet.Cells[3, k] = "0";
            //    k++;
            //}

            //start = s.StartDate;
            //k = 2;
            ////evaluations : answers

CQA/Views/Setups/Create.cshtml
@model CQA.Models.Setup

@{
    ViewBag.Title = "Vytvoriť setup";
}

<h2>Vytvoriť setup</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Setup</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label" style="float:left; margin-right: 15px; margin-top: 3px; margin-bottom: 10px;">
            @Html.LabelFor(model => model.Active)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Active)
            @Html.ValidationMessageFor(model => model.Active)
        </div>
        <div style="clear:both"/>

        <div class="editor-label" style="float:left; margin-right: 15px; margin-top: 3px; margin-bottom: 10px;">
            @Html.LabelFor(model => model.Displayed)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Displayed)
            @Html.ValidationMessageFor(model => model.Displayed)
        </div>
        <div style="clear:both"/>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnsweringProbability)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AnsweringProbability)
            @Html.ValidationMessageFor(model => model.AnsweringProbability)
        </div>

        <div style="clear:both"/>
        <div class="editor-label">
            @Html.LabelFor(model => model.SubjectId)
        </div>
        <div class="editor-field">
            @Html.DropDownList("SubjectId", String.Empty)
            @Html.ValidationMessageFor(model => model.SubjectId)
        </div>

        <p>
            <button type="submit" class="btn">Vytvoriť setup</button>
        </p>
    </fieldset>
}


<div>
    @Html.ActionLink("Späť na setupy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CQA/Views/Setups/Delete.cshtml
@model CQA.Models.Setup

@{
    ViewBag.Title = "Vymazať setup";
}

<h2>Vymazať setup</h2>

<h3>Naozaj chcete vymazať setup  @Html.DisplayFor(model => model.Name) z predmetu @Html.DisplayFor(model => model.Subject.Name)?</h3>
<h4>(Vymazaním setupu sa vymažú aj všetky otázky tohto setupu)</h4>

@using (Html.BeginForm()) {
    <p>
        <button type="submit" class="btn"> Vymazať setup</button> |
        @Html.ActionLink("Späť na setupy", "Index")
    </p>
}

CQA/Views/Setups/Details.cshtml
@model CQA.Models.Setup

@{
    ViewBag.Title = "Details";
}

@section Styles {
    @Styles.Render("~/Content/themes/base/css")
}

<h2>Details</h2>
Pridať odpovede
<form action="@Url.Action("AddAnswers", "Setups")" method="post" enctype="multipart/form-data" >
    <input name="file" type="file" accept=".csv" />
    <input type="hidden" name="setupId" value="@Model.SetupId" />
    <button type="submit" class="btn btn-primary">Pridať odpovede</button>
</form>

Koncepty:
<div id="concepts">
@{
    <div id="conceptsList">
        @foreach (var concept in Model.Subject.Concepts.OrderBy(c => c.Value)){
            <div style="float:left">
                <span class="existingConcept" >@(concept.Value)
                    <span style="margin-left:10px; cursor:pointer;" class="deleteConcept">x</span>
                </span>
                <input type="hidden" class="conceptId" value="@concept.ConceptId" />
            </div>
        }
    </div>
    <div style="clear:both"></div>
}
</div>
Pridať koncept:
@using (Ajax.BeginForm(null, null, new AjaxOptions()
{
    HttpMethod = "POST",
    Url = Url.Action("AddConcept", "Subjects"),
    OnSuccess = "AddConcept(data)"
},
new { autocomplete = "off" }))
{
    <input name="SubjectId" type="hidden" value="@Html.DisplayFor(model => model.SubjectId)"/>
    <input id="newConcept" name="Value" />
    <button id="addConcept" type="submit" class="btn btn-default">Pridať koncept</button>
}

<hr />
<p>Začiatok semestra:</p>
@using (Ajax.BeginForm(null, null, new AjaxOptions()
{
    HttpMethod = "POST",
    Url = Url.Action("SetStartDate", "Setups"),
},
new { autocomplete = "off" }))
{
    <input type="text" name="date" value="@Html.DisplayFor(model => model.StartDate)" id="datepicker">
    <input name="setupId" type="hidden" value="@Html.DisplayFor(model => model.SetupId)"/>
    <button type="submit" class="btn" style="position:relative; top: -6px">Nastaviť</button>
}
<hr />
<table id="conceptWeeks">
    @{
        <tr>
            <td></td>
            @for (int i = 0; i < 13; i++)
            {
                <td style="text-align:center">@(i+1)</td>
            }
        </tr>
        foreach (var concept in Model.Subject.Concepts.OrderBy(c => c.Value))
        {
            <tr class="concept" id="@("c"+concept.ConceptId)">
                <td class="conceptValue">@(concept.Value) (@concept.Questions.Count())</td>
                
                @for (int i = 0; i < 13; i++)
                {
                    
                    string style = "";
                    if (Model.StartDate.AddDays(7 * i) <= DateTime.Now && Model.StartDate.AddDays(7 * i +6) >= DateTime.Now)
                    {
                        style = "style=\"background: green;\"";
                    }
                    <td @Html.Raw(style)>        
                    @if (concept.ActiveWeeksList.Contains(i))
                    {
                        <input type="checkbox" class="activeCheckbox"  checked data-week="@i" data-conceptId="@concept.ConceptId" />
                    }
                    else
                    {
                        <input type="checkbox" class="activeCheckbox" data-week="@i" data-conceptId="@concept.ConceptId" />
                    }
                    </td>
                }
          </tr>
        }
    }
    <tr>
        <td></td>
     @for (int i = 0; i < 13; i++)
     {
         List<CQA.Models.Question> questions = new List<CQA.Models.Question>();
         foreach (var concept in Model.Subject.Concepts)
         {

             if (concept.ActiveWeeksList.Contains(i))
             {
                 foreach (var q in concept.Questions)
                 {
                     if (!questions.Contains(q))
                     {
                         questions.Add(q);
                     }
                 }
             }
         }
         <td id="weekTotal@(i)">@questions.Count()</td>;
     }
     </tr>
</table>
<hr />

 
<!--
<fieldset>
    <legend>Setup</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Active)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Active)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Subject.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Subject.Name)
    </div>
</fieldset> -->
<p>
    @Html.ActionLink("Stats", "GetBasicStatistics") |
    @Html.ActionLink("Edit", "Edit", new { id = Model.SetupId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        
        function AddConcept(data){
            var concept = $("#newConcept").val()
            $("#newConcept").val("")
            if(concept != "")
                $("#conceptsList").append('<div class="existingConcept">' + concept + '</div>')
            $("#conceptWeeks").append(data["conceptWeeks"]);


        }
       $(document).ready(function (){
 

           $(document).on("click", ".activeCheckbox", function (e) {
               if ($(e.target).is(":checked"))
                   activateConcept($(e.target).attr("data-conceptId"), $(e.target).attr("data-week"));
               else
                   deactivateConcept($(e.target).attr("data-conceptId"), $(e.target).attr("data-week"));
           });

           $(document).on("click", ".deleteConcept", function (e) {
               var id = $(e.target).parent().siblings(".conceptId").val();
               $(e.target).parent().parent().remove();
               $("#c"+id).remove();
               
               $.ajax({
                   url: "@Url.Action("RemoveConcept", "Subjects")",
                   method: "post",
                   contentType: "json",
                   data: '{"ConceptId":' + id+'}'
               });
           });

           function activateConcept(conceptId, week) {
               $.ajax({
                   url: "@Url.Action("ActivateConcept", "Subjects")",
                   method: "post",
                   contentType: "json",
                   data: '{"ConceptId":' + conceptId + ', "ActiveWeeks":"' + week + '"}',
                   success: refresh
               })
           }

           function deactivateConcept(conceptId, week) {
               $.ajax({
                   url: "@Url.Action("DeactivateConcept", "Subjects")",
                   method: "post",
                   contentType: "json",
                   data: '{"ConceptId":' + conceptId + ', "ActiveWeeks":"' + week + '"}',
                   success: refresh
               })
           }

           function refresh(res) {
               $("#weekTotal" + res["week"]).html(res["weekQuestionsCount"]);
           }

            $(function () {
                $("#datepicker").datepicker();
            });
        });
    </script>
}

CQA/Views/Setups/GetBasicStatistics.cshtml
@{
    ViewBag.Title = "GetBasicStatistics";
}

<h2>Súbor so štatistikami</h2>

<a href=" @ViewBag.Link " target="_blank">Stiahnuť súbor</a>

CQA/Views/Setups/GetReport.cshtml
@{
    ViewBag.Title = "GetReport";
}

<h2>GetReport</h2>

<a href=" @ViewBag.Link " target="_blank">Stiahnuť súbor</a>

CQA/Views/Setups/Questions.cshtml
@model IEnumerable<CQA.Models.Question>

@{
    ViewBag.Title = "Zoznam otázok";
}
@section Styles {
    @Styles.Render("~/Content/themes/base/css")
}


<h2>Otázky pre setup @(ViewData["SetupName"]), z predmetu  @(ViewData["SubjectName"])</h2>

<form action="@Url.Action("AddQuestions", "Setups")" method="post" enctype="multipart/form-data" >
    <input name="file" type="file" accept=".csv" />
    <input type="hidden" name="setupId" value="@(ViewData["SetupId"])" />
    <button type="submit" class="btn btn-primary">Pridať otázky</button>
</form>



@foreach (var item in Model)
{
    <div class="questionInList">
        <div style="float: left; margin-right: 20px;">
            <div style="text-align: center">@item.Answers.Count()</div>
            <div>
                @if (item.Answers.Count() == 1)
                { @Html.Raw("Odpoveď")}
                else if (item.Answers.Count() > 1 && item.Answers.Count() < 5)
                {
                    @Html.Raw("Odpovede")
                }
                else
                {
                    @Html.Raw("Odpovedí")
                }
            </div>
        </div>
        <span style="line-height: 40px; font-size: 10px; vertical-align: central">
            @if (@item.IsActive)
            {
                @("Aktívna")
            }
            else
            {
                @("Neaktívna")
            }
        </span>
        <span style="line-height: 40px; font-size: 20px; vertical-align: central">@item.QuestionText </span>
        <div class="conceptList">
            Priradené koncepty: 
            @foreach (var concept in item.Concepts)
            {
                <span>
                    <span class="concept">@(concept.Value)</span>
                    <input type="hidden" class="questionId" value="@item.QuestionId" />
                    <input type="hidden" class="conceptId" value="@concept.ConceptId" />
                    <b class="removeConcept">x</b>
                </span>
            }
        </div>

        <form>
            <input name="questionId" class="questionId" type="hidden" value="@(item.QuestionId)" />
            <input class="concepts" />
        </form>
    </div>
}

<br />
<div>
    @Html.ActionLink("Späť na setupy", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $(".concepts").each(function () {
                var thisEl = $(this);
                thisEl.autocomplete({
                    source: function (request, response) {
                        $.getJSON("@Url.Action("SearchConcepts", "Subjects")?subjectId=@(ViewData["SetupId"])&term=" + request.term + "&questionId=" + thisEl.siblings(".questionId").val(),
                              response);
                    },
                    minLength: 2,
                    select: function (event, ui) {
                        $.ajax({
                            url: "@Url.Action("AssignConceptToQuestion", "Subjects")",
                            method: "post",
                            contentType: "application/json; charset=utf-8",
                            dataType: "text",
                            data: '{"ConceptId":' + ui.item.id + ', "QuestionId":' + $(event.target).siblings(".questionId").val() + '}',
                            success: function (data) { $(event.target).parent().parent().children(".conceptList").append(data)  }
                        });
                }
                });
            });

            $(document).on("click", ".removeConcept", function (event) {

                $.ajax({
                    url: "@Url.Action("RemoveConceptFromQuestion", "Subjects")",
                    method: "post", contentType: "json",
                    data: '{"ConceptId":' + $(event.target).siblings(".conceptId").val() + ', "QuestionId":' + $(event.target).siblings(".questionId").val() + '}',
                    success: function () { $(event.target).parent().remove() }
                })
            });
        });
    </script>
}

CQA/Views/Setups/ShowStudents.cshtml
@model List<CQA.Models.UserProfile>
@{
    ViewBag.Title = "Zoznam študentov";
}

<h2>Študenti (@ViewBag.SetupName ):</h2>

@foreach (var u in Model)
{
    <a href="@Url.Action("ShowStudentsDetail","Setups",new {setupId = ViewBag.SetupId, userId = u.UserId})">
        <div style="border-bottom: 1px #808080 solid; cursor: pointer">    
            <h5 style="margin-bottom: 2px;">@(u.RealName.Split(' ')[1] + " " + u.RealName.Split(' ')[0])</h5>
            <span>#hodnoteni: <b>@(u.Evaluations.Count())</b> #odpovedi: <b>@(u.Answers.Count())</b> #komentárov: <b>@(u.Comments.Count())</b></span>
       </div>
    </a>
}