CQA/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using CQA.Resources;

namespace CQA.Models
{
    public class Question
    {

        public int QuestionId { get; set; }

        public int QuestionFileId { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.MultilineText)]
        public string QuestionText { get; set; }

        public string Hint { get; set; }

        public string ImageUri { get; set; }

        public bool IsActive { get; set; }

        public int SubjectId { get; set; }
        public virtual Subject Subject { get; set; }

        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<UsersAction> UsersActions { get; set; }
        public virtual ICollection<QuestionView> QuestionViews { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }

    }
}

CQA/Models/QuestionView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CQA.Models
{
    public class QuestionView
    {

        public int UserId { get; set; }
        public virtual UserProfile User { get; set; }

        public int QuestionId { get; set; }
        public virtual Question Question { get; set; }

        public DateTime ViewDate { get; set; }

    }
}

CQA/Models/Subject.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CQA.Models
{
    public class Subject
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int SubjectId { get; set; }

        [Required]
        [DisplayName("Meno predmetu")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Skrátené meno")]
        public string Shortcut { get; set; }


        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Setup> Setups { get; set; }
        public virtual ICollection<Concept> Concepts { get; set; }
    }
}

CQA/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CQA.Models;
using WebMatrix.WebData;
using System.DirectoryServices.Protocols;
using System.Security.Permissions;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices;

namespace CQA.Controllers
{

    public enum UserActionType
    {
        Evaluation = 1,
        Answering,
        ShowHint,
        SkippedAnswering,
        SkippedEvaluation

    }

    [Authorize]
    public class QuestionsController : Controller
    {


        private CQADBContext db = new CQADBContext();

        //
        // GET: /Questions/

        public ActionResult Index()
        {
           
           //Else return unfortunately there is nothing to return 
            return Json(false);
          
        }

        //
        // GET: /Questions/Details/5

        public ActionResult Details(int id = 0)
        {

            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // GET: /Questions/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Questions/Create

        [HttpPost]
        public ActionResult Create(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Questions.Add(question);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(question);
        }

        //
        // GET: /Questions/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Questions/Edit/5

        [HttpPost]
        public ActionResult Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(question);
        }

        //
        // GET: /Questions/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        //
        // POST: /Questions/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            db.Questions.Remove(question);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult CreateAnswer(int questionId, string text)
        {
            if (ModelState.IsValid)
            {
                if (db.Answers.Where(a => a.QuestionId == questionId && a.UserId == WebSecurity.CurrentUserId).Any())
                {
                    ModelState.AddModelError("", "Na otázku ste už odpovedali");
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(false);
                }

                var answer = new Answer();
                answer.UserId = WebSecurity.CurrentUserId;// = db.UserProfiles.Find(WebSecurity.CurrentUserId);
                answer.QuestionId = questionId;//db.Questions.Find(questionId);
                answer.Text = text;
                db.Answers.Add(answer);
                db.SaveChanges();

                UserMadeAction((int)UserActionType.Answering, 0,questionId);

                object result = new { answerText = text, answerAuthor = db.UserProfiles.Find(WebSecurity.CurrentUserId).RealName, answerId = answer.AnswerId };
                return Json(result);
            }
            else
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(false);
            }
        }

        [HttpGet]
        public ActionResult GetHint(int questionId)
        {
            Question q = db.Questions.Find(questionId);
            if(q != null && q.Hint != null){

                if (!db.UsersActions.Where(usa => usa.UserId == WebSecurity.CurrentUserId && usa.QuestionId == questionId).Any())
                {
                    UserMadeAction((int)UserActionType.ShowHint, 0,questionId);
                }

                return Json(new { Hint = db.Questions.Find(questionId).Hint }, JsonRequestBehavior.AllowGet);
            }
            else{
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult CreateEvaluation(int answerId, int value)
        {
            if (ModelState.IsValid)
            {
                if (db.Ratings.Where(a => a.AnswerId == answerId && a.UserId == WebSecurity.CurrentUserId).Any())
                {
                    ModelState.AddModelError("", "Odpoveď ste už hodnotili");
                    Response.StatusCode = (int)HttpStatusCode.BadRequest;
                    return Json(false);
                }

                var e = new Evaluation();
                e.UserId= WebSecurity.CurrentUserId;
                e.AnswerId = answerId;
                e.Value = (double)value/100;
                db.Ratings.Add(e);
                db.SaveChanges();

                //Mark action
                UserMadeAction((int)UserActionType.Evaluation, answerId,0);
            }



            return Json(true);
        }

        private void UserMadeAction(int action, int answerId, int questionId)
        {
            UsersAction ua = new UsersAction();
            ua.UserId = WebSecurity.CurrentUserId;

            if (answerId != 0)
            {
                ua.AnswerId = answerId;
            }
            else
            {
                ua.QuestionId = questionId;
            }
            
            ua.Action = action;
            db.UsersActions.Add(ua);
            db.SaveChanges();
        }

        [HttpGet]
        public ActionResult AnswerAndEvaluate(int setupId)
        {

            if (db.UsersSetups.Where( us => us.UserId == WebSecurity.CurrentUserId && us.SetupId == setupId ).ToList() == null)
            {
                UsersSetup us = new UsersSetup();
                us.UserId = WebSecurity.CurrentUserId;
                us.Score = 0;
                us.SetupId = setupId;
                db.UsersSetups.Add(us);
            }

            Random rand = new Random();
            if (rand.Next(4) != 4)
            {
                //user is going to validate answer
                var answers = db.Answers.OrderByDescending(a => a.Evaluations.Count())
                                    .Where(a =>/* !a.Evaluations.Where(r => r.UserId == WebSecurity.CurrentUserId).Any()) &&*/ a.Evaluations.Count() < 17 && a.Question.SetupId == setupId);
                var res = answers.ToList();
                if (res.Any())
                {
                    int n = res.First().Evaluations.Count();
                    var bestRatedAnswers = res.Where(a => a.Evaluations.Count() == n);
                    return View("Evaluate", bestRatedAnswers.ElementAt(rand.Next(bestRatedAnswers.Count())));

                }
            }

            var questions = db.Questions.OrderBy(q => q.Answers.Count())
                                .Where(q => !q.Answers.Where(r => r.UserId == WebSecurity.CurrentUserId).Any() && q.SetupId == setupId );
            var res2 = questions.ToList();
            if (res2.Any())
            {
                int n = res2.First().Answers.Count();
                var worstAnsweredQuestions = res2.Where(a => a.Answers.Count() == n);
                return View("Answer", worstAnsweredQuestions.ElementAt(rand.Next(worstAnsweredQuestions.Count())));

            }
            return Json(false);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CQA/Views/Subjects/Create.cshtml
@model CQA.Models.Subject

@{
    ViewBag.Title = "Vytvoriť predmet";
}

<h2>Vytvoriť predmet</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Subject</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Shortcut)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Shortcut)
            @Html.ValidationMessageFor(model => model.Shortcut)
        </div>

        <p>
            <button type="submit" class="btn">Vytvoriť predmet</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Späť na predmety", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CQA/Views/Subjects/Delete.cshtml
@model CQA.Models.Subject

@{
    ViewBag.Title = "Vymazať predmet";
}

<h2>Vymazať predmet</h2>

<h3>Naozaj chcete vymazať predmet  @Html.DisplayFor(model => model.Name) ?</h3>
<h4>(Vymazaním predmetu sa vymažú aj všetky setupy tohoto predmetu)</h4>

@using (Html.BeginForm()) {
    <p>
        <button type="submit" class="btn"> Vymazať predmet </button> | 
        @Html.ActionLink("Späť na predmety", "Index")
    </p>
}

CQA/Views/Subjects/Details.cshtml
@model CQA.Models.Subject

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Subject</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Shortcut)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Shortcut)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SubjectId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

CQA/Views/Subjects/Edit.cshtml
@model CQA.Models.Subject

@{
    ViewBag.Title = "Editovať predmet";
}

<h2>Editovať predmet</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Subject</legend>

        @Html.HiddenFor(model => model.SubjectId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Shortcut)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Shortcut)
            @Html.ValidationMessageFor(model => model.Shortcut)
        </div>

        <p>
            <button type="submit" class="btn">Uložiť zmeny</button>
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Späť na predmety", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CQA/Views/Subjects/Index.cshtml
@model IEnumerable<CQA.Models.Subject>

@{
    ViewBag.Title = "Predmety";
}

<h2>Predmety</h2>

<p>
    @Html.ActionLink("Pridať predmet", "Create", null ,new { @class = "btn" })
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shortcut)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shortcut)
        </td>
        <td>
            @Html.ActionLink("Editovať", "Edit", new { id=item.SubjectId }) |
            @Html.ActionLink("Otázky","Questions", new { id=item.SubjectId }) |
            @Html.ActionLink("Vymazať", "Delete", new { id=item.SubjectId })
        </td>
    </tr>
}

</table>

CQA/Views/Subjects/QuestionDetail.cshtml
@model  CQA.Models.Question

@section Styles{
    @Styles.Render("~/Content/themes/base/css")
}

@{
    ViewBag.Title = "Detail odpovedí na otázku:";
}

<h3>Detail otázky:</h3>
<h4>@(Model.QuestionText)</h4>
@if(Model.ImageUri != "")
{
    <img src="@Model.ImageUri" style="max-height: 350px;" />    
}

<h4>Odpovede:</h4>
<div class="header">
    <div class="header_value">
        Hodnotenie
    </div>
    <div class="header_qa">Odpoveď</div>
    <div style="float: right"><button class="expandAll">Skryť detaily</button></div>
    <div style="clear: both"></div>
</div>
@{
    int i = 0;
    foreach (var a in Model.Answers.Where(a => a.Evaluations.Count > 0).OrderByDescending(a => a.Evaluations.Count()))
    {
        i++;
     
    <div class="myAnswerWrap " id="a@(a.AnswerId)">
        <div class="myAnswer
                @if (i % 2 == 0)
                {@(" greyBackground")}" 
                @if (i == 1)
                {@Html.Raw("style=\"border-top: 1px solid lightgrey;\"")} >

            <div class="evalValueWrap" style="background: white">
                <div class="evalValue">
                    <div class="evalValueBg">
                        <div class="cleanValue"></div>

                        @{
                int n = a.Evaluations.Count(); 
                            <div class="evalsCount">@(n)
                                @if (n == 1)
                                {
                                    @("hodnotenie");
                                }
                                else if (n < 5)
                                {
                                    @("hodnotenia");
                                }
                                else
                                {
                                    @("hodnotení");
                                }
                            </div>
                                n = a.Comments.Count();
                            <div class="commentsCount">
                                @(a.Comments.Count())
                                @if (n == 1)
                                {
                                    @("komentár");
                                }
                                else if (n < 5 && n > 0)
                                {
                                    @("komentáre");
                                }
                                else
                                {
                                    @("komenatárov");
                                }
                            </div>
                        }

                    </div>
                </div>
            </div>

            <div class="elipsis" style="border-left: 1px solid lightgrey;">@Html.Raw(a.Text.Replace("&lt;br /&gt;", "<br />"))

                @if (a.Author == null)
                {
                    <span style="color:#b7170b">(old)</span>
                }
                else
                {
                    <span style="color:#168813">(new)</span>
                }
            </div>
            <div class="detail btn" title="Zobraziť detail">
                ››
            </div>
            <div style="clear: both"></div>
        </div>
        <div class="toggleDetails">
            <input type="hidden" value="@(a.Evaluations.Count())" name="count" class="count" />
            <input type="hidden" value="@((int)(a.GetAvgEvaluation() * 100))" name="numValue" class="numValue" />
            <div class="textValue"></div>
            <div class="sliderWrap">
                <div class="ui-widget-content-wrapper" style="width: 100%; margin-top: 25px;">
                    @foreach (var e in a.Evaluations)
                    {
                        int value = (int)(e.Value * 100);
                        int margin = 0;

                        if (value >= 50)
                        {
                            margin = -14;
                        }
                        else
                        {
                            margin = -8;
                        }

                        if (e.UserId == WebSecurity.CurrentUserId)
                        {
                        <div class="myEvaluationWrap" style="left:@(value)%; margin-left: @(margin)px;">
                            <div class="myEvaluationText">Vaše hodnotenie</div>
                            <div class="downArrow">›</div>
                            <div class="crowdSlider myEvaluation"></div>
                        </div>
                                
                        }
                        else if (Roles.IsUserInRole(CQA.Membership.CustomMembershipProvider.GetUser(e.UserId).UserName, "Admin") && CQA.Membership.CustomMembershipProvider.GetUser(e.UserId).UserName != "xlanim")
                        {
                        <div class="authorityEvaluationWrap" style="left:@(value)%; margin-left: @(margin)px;">
                            <div class="crowdSlider authorityEvaluation"></div>
                            <div class="upArrow">›</div>
                            <div class="myEvaluationText" style="margin-left: -65px; margin-top: -2px;">Hodnotenie učiteľa</div>
                        </div> 
                        }
                        else
                        {
                        <div class="crowdSlider" style="left:@(value)%; margin-left: @(margin)px; "></div>
                        }
                    }
                    <div class="slider-range"></div>
                </div>
            </div>
            <div style="clear: both"></div>
            <div style="text-align: center; width: 100%; margin-top: 20px;">Počet hodnotení odpovede: <b class="evalsCount">@(a.Evaluations.Count())</b></div>
            <div class="commentsWrap">
                <div class="comments" style="margin-left: 15px; margin-top: 5px; width: 96%;">
                    <h5 style="margin: 0; margin-top: 5px; margin-bottom: 5px">Komentáre:</h5>
                    @if (a.Comments.Any())
                    {
                        foreach (CQA.Models.Comment c in a.Comments)
                        {
                                    
                        <div class="comment">
                            <b>
                                @if (c.Anonymous)
                                {
                                    @("Anonym:") 
                                }
                                else
                                {
                                    @(c.Author.RealName + ":")
                                }
                            </b>
                            @Html.Raw(c.Text.Replace("&lt;br /&gt;", "<br />"))
                        </div>
                        }
                    }
                    else
                    {
                        <div class="noComments">K odpovedi neboli zatiaľ vytvorené žiadne komentáre</div>
                    }
                </div>
                <div class="commentForm">
                    @{Html.RenderPartial("_CreateCommentForm", new CQA.Models.Comment(a.AnswerId));}
                </div>
            </div>
        </div>
    </div>
    }
}


@section Scripts{
    @Scripts.Render("~/Scripts/jquery.dotdotdot.min.js")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")

    <script type="text/javascript">

        function CommentCreated(data) {
            $("#a" + data.AnswerId).find('.noComments').hide();
            $("#a" + data.AnswerId).find('textarea').val('');
            $("#a" + data.AnswerId).find(".comments").append('<div class="comment empAnswer"><b>' + data.UserName + ':</b> ' + data.Text + '</div>');
        }

        $(document).ready(function () {

            $("#filter").change(function () {
                var options = $("#filter option");
                var idx = options.index(options.filter(":selected"));
                if (idx == 1) {
                    $(".answered").each(function () {
                        $(this).show();
                    });
                    $(".evaluated").each(function () {
                        $(this).hide();
                    });
                }
                else if (idx == 0) {
                    $(".answered").each(function () {
                        $(this).hide();
                    });
                    $(".evaluated").each(function () {
                        $(this).show();
                    });
                }
                else if (idx == 2) {
                    $(".answered").each(function () {
                        $(this).show();
                    });
                    $(".evaluated").each(function () {
                        $(this).show();
                    });
                }
            });

            $(".toggleDetails").each(function () {
                //alert($(this).children(".numValue").val())
            });

            $(".elipsis").dotdotdot();

            $(".slider-range").slider({
                range: false,
                min: 0,
                max: 100,
                value: 50,
            });
            $(".slider-range").slider('disable');


            //Hides dialog by clicking outside of it
            $('body').on("click", '.ui-widget-overlay', function () {
                $("#dialog").dialog("close");
            });

            $(".myAnswer").each(function () {
                var parent = $(this).parent()
                var val = parent.find(".numValue").val();
                $(this).find(".evalValue").css("background", getColorWithOpacity(val, parent.find(".count").val()));
                changeText(parent.find(".cleanValue"), val);
                showDetail(this);
            });


            $(".myAnswer").click(function () {

                //alert($(this).children(".numValue"));
                showDetail(this)

            });

            $(".expandAll").click(function () {
                if ($(this).html() == "Skryť detaily") {
                    $(".myAnswer").each(function () {
                        $(this).parent().find(".toggleDetails").hide();
                    });
                    $(this).html("Zobraziť detaily")
                }
                else {
                    $(".myAnswer").each(function () {
                        $(this).parent().find(".toggleDetails").show();
                    });
                    $(this).html("Skryť detaily")
                }
            });

            function showDetail(el) {
                var parent = $(el).parent()
                var val = parent.find(".numValue").val();
                changeText(parent.find(".textValue"), val);
                parent.find(".slider-range").slider('value', val);
                parent.find(".ui-widget-content-wrapper").css("background", getColor(val));
                $(el).parent().find(".toggleDetails").slideToggle();
            }

            function changeText(el, val) {
                if (val < 10)
                    el.html("Silný nesúhlas")
                else if (val < 26) {
                    el.html("Nesúhlas")
                    el.addClass("evalValueOneRow")
                }
                else if (val < 42)
                    el.html("Skôr nesúhlas")
                else if (val < 58) {
                    el.html("Čiastočný súhlas")
                }
                else if (val < 74) {
                    el.html("Skôr súhlas")
                    el.addClass("evalValueOneRow")
                }
                else if (val < 90) {
                    el.html("Súhlas")
                    el.addClass("evalValueOneRow")
                }
                else
                    el.html("Silný súhlas")
            }

            function getColorWithOpacity(val, evalsCount) {
                if (evalsCount < 10)
                    opacity = 10 - evalsCount;
                else
                    opacity = 1;
                if (val > 50)
                    return "rgba(" + (220 - ((val - 50) * 4)) + ", 180, 20, " + (0.2 + (0.8 / opacity)) + ")"
                else
                    return "rgba( 220, " + (180 - Math.ceil((50 - val) * 3.5)) + ", 20, " + (0.2 + (0.8 / opacity)) + ")"
            }

            function getColor(val) {
                if (val > 50) {
                    return "rgb(" + (220 - ((val - 50) * 4)) + ", 180, 20)"
                }
                else {
                    return "rgb( 220, " + Math.ceil(180 - ((50 - val) * 3.5)) + ", 20)"
                }
            }

        });
    </script>
}