CQA/Models/Answer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CQA.Resources;

namespace CQA.Models
{
    public class Answer : DateCreatedModel
    {
        public int AnswerId { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        public string Text { get; set; }

        public double ExpertRating { get; set; }

        public int QuestionId { get; set; }
        public virtual Question Question { get; set; }

        public int UserId { get; set; }
        public virtual UserProfile Author{ get; set; }

        /// <summary>
        /// Flag for determining if Answer have enough evaluations to be displayed to author
        /// NULL = not enough ratings
        /// False = enough ratings but not seen
        /// True = already seen
        /// </summary>
        public bool? SeenEvaluation { get; set; }

        public virtual ICollection<Evaluation> Evaluations { get; set; }
        public virtual ICollection<UsersAction> UsersActions { get; set; }


        public double GetAvgEvaluation()
        {
            double total = 0;
            foreach (var e in this.Evaluations)
            {
                total += e.Value;
            }
            return total / this.Evaluations.Count();
        }

    }

    public class CreateAnswer
    {

        public CreateAnswer(int questionId)
        {
            this.QuestionId = questionId;
        }

        [Required]
        [HiddenInput(DisplayValue = false)]
        public int QuestionId { get; set; }

        [DataType(DataType.MultilineText)]
        [DisplayName("Vaša odpoveď:")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        public string Text { get; set; }

    }
}

CQA/Controllers/QuestionsAndAnswersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CQA.Models;
using WebMatrix.WebData;
using System.DirectoryServices.Protocols;
using System.Security.Permissions;
using System.DirectoryServices.AccountManagement;
using System.DirectoryServices;
using System.Web.Script.Serialization;
using System.IO;

namespace CQA.Controllers
{

    public class QuestionsAndAnswersController : Controller
    {

        private CQADBContext db = new CQADBContext();

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateAnswer(int questionId, string text, int setupId)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RemoveHandledObjectFromSession(false);

                    if (db.Answers.Where(a => a.QuestionId == questionId && a.UserId == WebSecurity.CurrentUserId).Any())
                    {
                        ModelState.AddModelError("", "Na otázku ste už odpovedali");
                        return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                    }

                    var answer = new Answer(questionId, HttpUtility.HtmlDecode(text), WebSecurity.CurrentUserId, setupId);
                    db.Answers.Add(answer);
                    db.SaveChanges();

                    UserMadeAction(UserActionType.Answering, 0, questionId, WebSecurity.CurrentUserId);
                    UserSeenQuestion(questionId, WebSecurity.CurrentUserId);

                    object result = new { answerText = text };
                    return Json(result);
                }
                else
                {
                    return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                }
            }
            catch (Exception e)
            {
                Error error = new Error(UserActionType.Answering, HttpUtility.HtmlEncode(text), e.Message);
                db.Errors.Add(error);
                db.SaveChanges();
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ExternCreateAnswer()
        {
            try
            {
                Answer ans = new JavaScriptSerializer().Deserialize<Answer>(Request.Form["json"]);

                if (!db.UserProfiles.Where(u => u.UserId == ans.UserId).Any() ||
                    db.Answers.Where(a => a.QuestionId == ans.QuestionId && a.UserId == ans.UserId).Any())
                {
                    return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                }

                ans.Text = HttpUtility.HtmlEncode(ans.Text);

                db.Answers.Add(ans);
                db.SaveChanges();

                UserMadeAction(UserActionType.Answering, 0, ans.QuestionId, (int)ans.UserId);
                UserSeenQuestion(ans.QuestionId, (int)ans.UserId);

                Question que = db.Questions.Single(q => q.QuestionId == ans.QuestionId);

                object result = new { answerText = HttpUtility.HtmlDecode(ans.Text).Replace("\"", "'"), answerId = ans.AnswerId, questionId = ans.QuestionId, questionFileId = que.QuestionFileId };
                return Json(result);
            }
            catch (Exception e)
            {
                Error error = new Error(UserActionType.Answering, HttpUtility.HtmlEncode(Request.Form["json"].ToString()), e.Message);
                db.Errors.Add(error);
                db.SaveChanges();
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult CreateEvaluation(int answerId, int value)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    RemoveHandledObjectFromSession(true);

                    if (db.Ratings.Where(a => a.AnswerId == answerId && a.UserId == WebSecurity.CurrentUserId).Any())
                    {
                        ModelState.AddModelError("", "Odpoveď ste už hodnotili");
                        return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                    }

                    //Notifications
                    Answer answer = db.Answers.Find(answerId);
                    CreateNotifications(answer, NotificationType.NewEvaluation, WebSecurity.CurrentUserId);

                    var e = new Evaluation(WebSecurity.CurrentUserId, answerId, (double)value / 100);
                    db.Ratings.Add(e);
                    db.SaveChanges();

                    //Mark action
                    UserMadeAction(UserActionType.Evaluation, answerId, 0, WebSecurity.CurrentUserId);
                    //Mark question as seen
                    UserSeenQuestion(answer.QuestionId, WebSecurity.CurrentUserId);

                    return Json(new { avgEval = answer.GetAvgEvaluation(), evalsCount = answer.Evaluations.Count(), comments = answer.GetAnswerComments() });
                }

                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            catch (Exception e)
            {
                Error error = new Error(UserActionType.Evaluation, "", e.Message);
                db.Errors.Add(error);
                db.SaveChanges();
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        public ActionResult ExternCreateEvaluation()
        {
            try
            {
                Evaluation eval = new JavaScriptSerializer().Deserialize<Evaluation>(Request.Form["json"]);
                eval.Value = eval.Value / (double)100;

                if (!db.UserProfiles.Where(u => u.UserId == eval.UserId).Any() ||
                    db.Ratings.Where(a => a.AnswerId == eval.AnswerId && a.UserId == eval.UserId).Any())
                {
                    return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
                }

                //Notifications
                Answer answer = db.Answers.Find(eval.AnswerId);
                CreateNotifications(answer, NotificationType.NewEvaluation, eval.UserId);

                db.Ratings.Add(eval);
                db.SaveChanges();

                //Mark action
                UserMadeAction(UserActionType.Evaluation, eval.AnswerId, 0, eval.UserId);
                //Mark question as seen
                UserSeenQuestion(eval.Answer.QuestionId, eval.UserId);

                return Json(new { avgEval = answer.GetAvgEvaluation(), evalsCount = answer.Evaluations.Count(), comments = answer.GetAnswerComments(true), answerId = eval.AnswerId });
            }
            catch (Exception e)
            {
                Error error = new Error(UserActionType.Evaluation, HttpUtility.HtmlEncode(Request.Form["json"].ToString()), e.Message);
                db.Errors.Add(error);
                db.SaveChanges();
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [ValidateInput(false)]
        public ActionResult CreateComment(Comment comment)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    comment.UserId = WebSecurity.CurrentUserId;
                    comment.Text = HttpUtility.HtmlEncode(comment.Text).Replace("\"", "'");
                    db.Comments.Add(comment);
                    db.SaveChanges();

                    Answer ans = db.Answers.Single(a => a.AnswerId == comment.AnswerId);
                    //Create Notification
                    CreateNotifications(ans, NotificationType.NewComment, comment.UserId);

                    //Mark action
                    UserMadeAction(UserActionType.Commented, comment.AnswerId, 0, WebSecurity.CurrentUserId);
                    ViewComment vc;
                    if (comment.Anonymous)
                        vc = new ViewComment(comment.Text, "Anonym", comment.AnswerId);
                    else
                        vc = new ViewComment(comment.Text, db.UserProfiles.Find(comment.UserId).RealName, comment.AnswerId);

                    vc.Text = vc.Text.Replace("&lt;br /&gt;", "<br />");

                    return Json(vc);

                }

                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            catch (Exception e)
            {
                Error error = new Error(UserActionType.Commented, HttpUtility.HtmlEncode(comment.Text), e.Message);
                db.Errors.Add(error);
                db.SaveChanges();
                return new HttpStatusCodeResult((int)HttpStatusCode.InternalServerError);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ExternCreateComment()
        {
            try
            {
                Comment comment = new JavaScriptSerializer().Deserialize<Comment>(Request.Form["json"]);
                comment.Text = HttpUtility.HtmlEncode(comment.Text);

                db.Comments.Add(comment);
                db.SaveChanges();

                Answer ans = db.Answers.Single(a => a.AnswerId == comment.AnswerId);
                //Create Notification
                CreateNotifications(ans, NotificationType.NewComment, comment.UserId);

                //Mark action
                UserMadeAction(UserActionType.Commented, comment.AnswerId, 0, comment.UserId);
                ViewComment vc;
                if (comment.Anonymous)
                    vc = new ViewComment(comment.Text, "Anonym", comment.AnswerId);

CQA/Views/QuestionsAndAnswers/AnswerWithHint.cshtml
@model CQA.Models.Question

@{
    ViewBag.Title = "Odpovedzte na otázku";
}


@section Styles {
        @Styles.Render("~/Content/themes/base/css")
}

<h3>Odpovedzte na otázku</h3>

<div class="question">
    <div id="questionText">
        <span style="font-size: 0.85em; font-weight:bold">Otázka: </span>
        @Html.DisplayFor(model => model.QuestionText)
        @if (Model.Hint != null)
        {
            <div id="hint"> @Ajax.ActionLink("Napovedať", "GetHint", "QuestionsAndAnswers", new { objectId = Model.QuestionId, evaluating=false }, new AjaxOptions
                       {
                           OnSuccess = "showHint(data)",
                           HttpMethod = "GET"
                       },
                       new { @class = "btn" })        
            </div>
        }
    </div>
</div>

 @{Html.RenderPartial("_CreateAnswerForm", new CQA.Models.CreateAnswer(Model.QuestionId));}
<div class="alert alert-success" style="display:none; text-align:center">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    Ďakujeme za odpoveď. Akonáhle bude k dispozícií spätná väzba, budete notifikovaný.
</div>
<div style="text-align:center; width: 100%">
    <a href="@Url.Action("AnswerAndEvaluate", new { setupId = Model.SetupId})" id="next" class="btn" style="display:none">Ďalšia otázka/hodnotenie</a>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/AnswerAndEvaluateCommon.js"></script>   
        <script>
            jQuery(document).ready(function ($) {
                $("#MenuSetupItem"+@(Model.SetupId)).addClass("activeMenuItem")
            })

            function AnswerCreated(data) {
                $("#answerText").prepend(data.answerText);
                $("#hint").fadeOut();
                $("#skip").fadeOut();
                $("#next").fadeIn();
                $('#submit').fadeOut();
                $(".alert").fadeIn();              
            }
    </script>
    <script src="~/Scripts/AnswerAndEvaluateCommon.js"></script>
}

CQA/Views/QuestionsAndAnswers/Evaluate.cshtml
@model CQA.Models.Answer

@{
    ViewBag.Title = "Ohodnoťte odpoveď";
}
@section Styles {
    @Styles.Render("~/Content/themes/base/css")
}

<h4>Ohodnotťe správnosť odpovede</h4>

<div class="question">

    <div id="questionText"><span style="font-size: 0.85em; font-weight: bold">Otázka: </span>@Html.DisplayFor(model => model.Question.QuestionText) </div>
    @if (Model.Question.ImageUri != null && Model.Question.ImageUri != "")
    {
        <a href="@Model.Question.ImageUri" target="_blank" style="color:darkblue; font-size:0.8em">(Zobraziť obrázok)</a>
    }
</div>
<div class="answer">
    <div id="answerText"><span style="font-size: 0.85em; font-weight: bold">Odpoveď: </span>@Html.Raw(Model.Text.Replace("&lt;br /&gt;","<br />"))</div>
</div>

<div style="text-align: center">
    @using (Ajax.BeginForm(null, null, new AjaxOptions()
    {
        HttpMethod = "POST",
        Url = Url.Action("CreateEvaluation", "QuestionsAndAnswers"),
        OnSuccess = "EvaluationCreated(data)"
    },
        new { autocomplete = "off" }))
    {
        @Html.AntiForgeryToken()
        <input name="answerId" type="hidden" value="@Html.DisplayFor(model => model.AnswerId)" />
        <input type="hidden" value="50" id="value" name="value" />
            
        <div id="sliderWrap">
            <div id="textValue">Čiastočne súhlasím</div>
            <div id="sliderInlineWrap">
                <img src="~/Images/thumbDown.png" class="thumb" id="thumbDown" />
                <div class="ui-widget-content-wrapper" style="background: rgb(220, 180, 20)">
                    <div id="crowdEvaluation">
                        <div id="crowdSliderWrap">
                            <div id="crowdSlider"></div>
                            <div id="crowdEvaluationText"></div>
                        </div>
                    </div>
                    <div class="slider-range" style=""></div>
                </div>
                <img id="thumbUp" src="~/Images/thumbUp.png" class="thumb" />
                <div style="clear: both"></div>
            </div>
        </div>
        <div style="clear: both"></div>
        <div class="alert alert-success" style="display: none">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Ďakujeme za hodnotenie. Vyššie si môžete pozrieť priemerné hodnotenie odpovede.
        </div>
        <a href="@Url.Action("AnswerAndEvaluate", new { setupId = ViewBag.setupId })" id="next" class="btn" style="display:none">Ďalšia otázka/hodnotenie</a>
        <a href="@Url.Action("SkipEvaluation", new { answerId = Model.AnswerId, setupId = ViewBag.setupId })" id="newAnswer" style="margin:0" class="btn skip">Preskočiť</a>
        <button type="submit" id="submit" class="btn btn-primary">Ohodnotiť</button>   
    }
    <div id="commentsSection">  
        <div id="comments">
            <h4>Komentáre:</h4>
        </div>
        <div id="commentForm">
            @{Html.RenderPartial("_CreateCommentForm", new CQA.Models.Comment(Model.AnswerId));} 
        </div>
    </div>
</div>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Scripts/jquery.ui.touch-punch.min.js")
  
    <script>

        function CommentCreated(data) {
            $('#commentForm').fadeOut();
            $('#noComments').hide();
            $("#comments").append('<div class="comment empAnswer"><b>'+ data.UserName +':</b> '+ data.Text +'</div>');

        }

        function EvaluationCreated(data)
        {
            if(data.evalsCount > 1)
                $("#crowdEvaluationText").html("Odpoveď davu z " + data.evalsCount+" hodnotení")
            else
            {
                //TODO Maybe change text when only one evaluation 
                $("#crowdEvaluationText").html("Odpoveď davu z " + data.evalsCount+" hodnotenia")
            }
           
            $("#crowdSliderWrap").css("margin-left", data.avgEval*100-6 + "%");
            $(".slider-range").slider('disable');
            $("#crowdEvaluation").fadeIn();
            $(".slider-range").parent().css("background", getColor(parseInt(data.avgEval*100)));
            $("#newAnswer").fadeOut();
            $("#next").fadeIn(); 
            $('#submit').fadeOut();
            $('#submit').attr('disabled', 'disabled');
            $(".alert").fadeIn();  

            commentsData = data["comments"];
            if(commentsData.length == 0)
                $("#comments").append('<div id="noComments">Zatiaľ neboli vytvorené žiadne komentáre</div>');
            else{
                $.each(commentsData, function (index, value) {
                    if(index % 2 == 1)
                        $("#comments").append('<div class="comment greyBackground"><b>'+ value.UserName +':</b> '+ value.Text +'</div>');
                    else
                        $("#comments").append('<div class="comment"><b>'+ value.UserName +':</b> '+ value.Text +'</div>');
                });
            }
            $("#commentsSection").fadeIn();

            $('html, body').animate({
                scrollTop: $("#commentsSection").offset().top - 330
            }, 1500);
        }

        function getColor(val) {
            //alert(val)
            if (val > 50)
                return "rgb(" + (220 - ((val - 50) * 4)) + ", 180, 20)"
            else
                return "rgb( 220, " + (180 - ((50 - val) * 3.5)) + ", 20)"
        }

        jQuery('#widget').draggable();
        jQuery(document).ready(function ($) {
           
            //******** Activity logging sectio *********
            //var start = new Date();
            //var totalIdle = 0;
            //var idleTime = 0;

            //function CreateActivityLogData()
            //{
            //    //Set hidden fields in form for this values
            //    elapsed = new Date() - start;
            //    //set totalIdle
            //}

            ////Counting total idle time
            //setInterval(function(){
            //    idleTime += 100
            //}, 100);
            ////Zero the idle timer on mouse movement.
            //$(this).mousemove(function (e) {
            //    totalIdle += idleTime;
            //    idleTime = 0;
            //});
            //$(this).keypress(function (e) {
            //    totalIdle += idleTime;
            //    idleTime = 0;
            //});

            $("#MenuSetupItem"+@(ViewBag.setupId)).addClass("activeMenuItem");

           $(".slider-range").each(function () { $(this).trigger('mySliderTrigger') })
           $(".slider-range").slider({
               range: false,
               min: 0,
               max: 100,
               value: 50,
               slide: function (event, ui) {
                   $("#value").val(ui.value);
                   changeColorAndText(); 
               }
           });
               
           $("#thumbDown").click(function(){
               if($('#submit').attr('disabled') != "disabled"){
                   var val = parseInt($("#value").val());
                   if(val < 5){
                       $(".slider-range").slider('value',0);
                       $("#value").val(0);
                   }
                   else{
                       $(".slider-range").slider('value',val-5);
                       $("#value").val(val-5);
                   }
                   changeColorAndText();
               }
           });
           $("#thumbUp").click(function(){
               if($('#submit').attr('disabled') != "disabled"){
                   var val = parseInt($("#value").val());
                   if(val > 95){
                       $(".slider-range").slider('value',100);
                       $("#value").val(100);
                   }
                   else{
                       $(".slider-range").slider('value',val+5);
                       $("#value").val(val+5);
                   }
                   changeColorAndText();
               }
           });

           function changeColorAndText(){
               var val = parseInt($("#value").val());
               $(".slider-range").parent().css("background", getColor(val));

               var el = $("#textValue");

               var el = $("#textValue");
               if (val < 10)
                   el.html("Silno nesúhlasím")
               else if (val < 26)
                   el.html("Nesúhlasím")
               else if (val < 42)
                   el.html("Skôr nesúhlasím")
               else if (val < 58)
                   el.html("Čiastočne súhlasím")
               else if (val < 74)
                   el.html("Skôr súhlasím")
               else if (val < 90)
                   el.html("Súhlasím")
               else
                   el.html("Silno súhlasím") 
           }             

       });
    </script>

}

CQA/Views/QuestionsAndAnswers/EvaluateWithHint.cshtml
@model CQA.Models.Answer

@{
    ViewBag.Title = "Ohodnoťte odpoveď";
}
@section Styles {
        @Styles.Render("~/Content/themes/base/css")
}

<h4>Ohodnotťe správnosť odpovede</h4>

<div class="question">
    
    <div id="questionText"> <span style="font-size: 0.85em; font-weight:bold">Otázka: </span> @Html.DisplayFor(model => model.Question.QuestionText) </div>
    @if (Model.Question.Hint != null)
    {

        <div id="hint"> @Ajax.ActionLink("Napovedať", "GetHint", "QuestionsAndAnswers", new { objectId = Model.AnswerId, evaluating=true }, new AjaxOptions
                    {
                        OnSuccess = "showHint(data)",
                        HttpMethod = "GET"
                    },
                    new { @class = "btn" })        
        </div>

    }
</div>
<div class="answer"> 
  <div id="answerText"> <span style="font-size: 0.85em; font-weight:bold">Odpoveď: </span>@Html.DisplayFor(model => model.Text)</div>
</div>

<div style="text-align:center">
        @using (Ajax.BeginForm(null, null, new AjaxOptions()
        {
            HttpMethod = "POST",
            Url = Url.Action("CreateEvaluation", "QuestionsAndAnswers"),
            OnBegin = "CreateActivityLogData()",
            OnSuccess = "EvaluationCreated(data)"
        },
        new { autocomplete = "off" }))
        {
            <input name="answerId" type="hidden" value="@Html.DisplayFor(model => model.AnswerId)" />
            <input type="hidden" value="50" id="value" name="value" />
            
            <div id="sliderWrap">
                <div id="textValue">Čiastočne správne</div>
                <div id="sliderInlineWrap">
                <img src="~/Images/thumbDown.png" class="thumb" id="thumbDown"/>
                <div class="ui-widget-content-wrapper">
                    <div id="crowdEvaluation"> 
                        <div id="crowdSliderWrap">
                            <div id="crowdSlider"></div>
                            <div id="crowdEvaluationText"> </div>
                         </div>
                    </div>
                    <div class="slider-range" style=""></div>
                </div> 
                <img id="thumbUp" src="~/Images/thumbUp.png" class="thumb"/>
                <div style="clear:both"></div>
                </div>
            </div>
         <div style="clear:both"></div>
            <div class="alert alert-success" style="display:none">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                Ďakujeme za hodnotenie. Vyššie si môžete pozrieť priemerné hodnotenie odpovede.
            </div>
            <a href="@Url.Action("AnswerAndEvaluate", new { setupId = Model.Question.SetupId })" id="next" class="btn" style="display:none">Ďalšia otázka/hodnotenie</a>
            <a href="@Url.Action("SkipEvaluation", new { answerId = Model.AnswerId, setupId = Model.Question.SetupId })" id="newAnswer" style="margin:0" class="btn skip">Preskočiť</a>
            <button type="submit" id="submit" class="btn btn-primary">Ohodnotiť</button>   
        }
    </div>
 


@section Scripts {

    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/Scripts/jquery.ui.touch-punch.min.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")


   <script src="~/Scripts/AnswerAndEvaluateCommon.js"></script>  
   <script>
       function EvaluationCreated(data)
       {
           $("#crowdEvaluationText").html("Odpoveď davu z " + data.evalsCount+" hodnotení")
           $("#crowdSliderWrap").css("margin-left", data.avgEval*100-6 + "%");
           $(".slider-range").slider('disable');
           $("#hint").fadeOut;
           $("#crowdEvaluation").fadeIn();
           $("#newAnswer").fadeOut();
           $("#next").fadeIn(); 
           $('#submit').attr('disabled', 'disabled');
           $(".alert").fadeIn();
          
           //TODO move crowd slider and display it
       }

       jQuery('#widget').draggable();
       jQuery(document).ready(function ($) {
           
           var start = new Date();
           var totalIdle = 0;
           var idleTime = 0;

           function CreateActivityLogData()
           {
               //Set hidden fields in form for this values
               elapsed = new Date() - start;
               //set totalIdle
           }


           //Counting total idle time
           setInterval(function(){
               idleTime += 100
           }, 100);
           //Zero the idle timer on mouse movement.
           $(this).mousemove(function (e) {
               totalIdle += idleTime;
               idleTime = 0;
           });
           $(this).keypress(function (e) {
               totalIdle += idleTime;
               idleTime = 0;
           });

           $("#MenuSetupItem"+@(Model.Question.SetupId)).addClass("activeMenuItem");

           $(".slider-range").each(function () { $(this).trigger('mySliderTrigger') })
               $(".slider-range").slider({
                   range: false,
                   min: 0,
                   max: 100,
                   value: 50,
                   slide: function (event, ui) {
                       $("#value").val(ui.value);
                       hex = hexFromRGB(10, 10, ui.value);
                       if (ui.value > 50) {
                           $(this).parent().css("background", "rgba(22, 149, 49, " + (ui.value - 50) * 2 / 100 + ")");
                       }
                       else {
                           $(this).parent().css("background", "rgba(143, 20, 20, " + (50 - ui.value) * 2 / 100 + ")");
                       }
                       var el = $("#textValue");
                       if (ui.value < 8)
                           el.html("Úplne nesprávne")
                       else if (ui.value < 36)
                           el.html("Takmer nesprávne")
                       else if (ui.value < 64)
                           el.html("Čiastočne správne")
                       else if (ui.value < 92)
                           el.html("Takmer správne")
                       else el.html("Úplne správne");
                           
                   }
               });

               
               $("#thumbDown").click(function(){
                   if($('#submit').attr('disabled') != "disabled"){
                       var val = parseInt($("#value").val());
                       if(val < 5){
                           $(".slider-range").slider('value',0);
                           $("#value").val(0);
                       }
                       else{
                           $(".slider-range").slider('value',val-5);
                           $("#value").val(val-5);
                       }
                   }
               });
               $("#thumbUp").click(function(){
                   if($('#submit').attr('disabled') != "disabled"){
                       var val = parseInt($("#value").val());
                       if(val > 95){
                           $(".slider-range").slider('value',100);
                           $("#value").val(100);
                       }
                       else{
                           $(".slider-range").slider('value',val+5);
                           $("#value").val(val+5);
                       }
                   }
  
               });
           });

       function hexFromRGB(r, g, b) {
           var hex = [
           r.toString(16),
           g.toString(16),
           b.toString(16)
           ];
           jQuery.each(hex, function (nr, val) {
               if (val.length === 1) {
                   hex[nr] = "0" + val;
               }
           });
           return hex.join("").toUpperCase();
       }
    </script>
       
}

CQA/Views/QuestionsAndAnswers/Index.cshtml
@model IEnumerable<CQA.Models.Question>

@{
    ViewBag.Title = "CQA";
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>


@foreach (var item in Model) {
   <div class="question"> 
       <div style="float:left; margin-right:20px;">
           <div style="text-align:center">@item.Answers.Count()</div>
           <div> @if(item.Answers.Count() == 1){ @Html.Raw("Odpoveď")}
                 else if (item.Answers.Count() > 1 && item.Answers.Count() < 5)
                 {
                     @Html.Raw("Odpovede")
                 }
               else{
                    @Html.Raw("Odpovedí")
               } 
           </div> </div> 
       
       <a href="@Url.Action("Details", new { id=item.QuestionId })"><span style="line-height:40px; font-size:20px; vertical-align:central">@item.QuestionText</span> </a>
   </div>

}